--######
USE ROLE ACCOUNTADMIN;
-- Enable logs, metrics and traces
ALTER DATABASE SIMPLE_MLOPS_DEMO SET LOG_LEVEL = INFO;
ALTER DATABASE SIMPLE_MLOPS_DEMO SET METRIC_LEVEL = ALL;
ALTER DATABASE SIMPLE_MLOPS_DEMO SET TRACE_LEVEL = ALWAYS;

-- Create warehouses
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE='X-SMALL';
CREATE WAREHOUSE IF NOT EXISTS FEATURE_STORE_WH WITH WAREHOUSE_SIZE='MEDIUM';
USE WAREHOUSE FEATURE_STORE_WH;

CREATE OR REPLACE NOTEBOOK SIMPLE_MLOPS_DEMO.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK 
FROM '@SIMPLE_MLOPS_DEMO.PUBLIC.GITHUB_REPOSITORY_SNOWFLAKE_SIMPLE_MLOPS/branches/main/src/' 
MAIN_FILE = 'SIMPLE_MLOPS_DEMO_NOTEBOOK.ipynb'
QUERY_WAREHOUSE = 'COMPUTE_WH';
ALTER NOTEBOOK SIMPLE_MLOPS_DEMO.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK  ADD LIVE VERSION FROM LAST;

-- Load demo data
CREATE OR REPLACE SCHEMA SIMPLE_MLOPS_DEMO._DATA_GENERATION;
CREATE OR REPLACE STAGE SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA;
COPY FILES
  INTO @SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA
  FROM @SIMPLE_MLOPS_DEMO.PUBLIC.GITHUB_REPOSITORY_SNOWFLAKE_SIMPLE_MLOPS/branches/main/_internal/data;

CREATE FILE FORMAT parquet_format
  TYPE = parquet;
  
CREATE OR REPLACE TABLE SIMPLE_MLOPS_DEMO._DATA_GENERATION.TRANSACTIONS AS 
SELECT * FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA',
        FILE_FORMAT => 'parquet_format'
    )
);

CREATE OR REPLACE TABLE SIMPLE_MLOPS_DEMO._DATA_GENERATION.TRANSACTIONS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
      FROM TABLE(
        INFER_SCHEMA(
          LOCATION=>'@SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA',
          FILE_FORMAT=>'parquet_format'
        )
      ));

COPY INTO SIMPLE_MLOPS_DEMO._DATA_GENERATION.TRANSACTIONS
FROM @SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME='CASE_INSENSITIVE';

DROP STAGE SIMPLE_MLOPS_DEMO._DATA_GENERATION.DATA;

CREATE OR REPLACE NOTEBOOK SIMPLE_MLOPS_DEMO.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK 
FROM '@SIMPLE_MLOPS_DEMO.PUBLIC.GITHUB_REPOSITORY_SNOWFLAKE_SIMPLE_MLOPS/branches/main/src/' 
MAIN_FILE = 'SIMPLE_MLOPS_DEMO_NOTEBOOK.ipynb'
QUERY_WAREHOUSE = 'COMPUTE_WH';
ALTER NOTEBOOK SIMPLE_MLOPS_DEMO.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK  ADD LIVE VERSION FROM LAST;